export const treatments = {
  cataract: {
    title: 'Cataract Surgery',
    subtitle: 'Restore Crystal-Clear Vision',
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=1200',
    overview: 'Cataract surgery is one of the most commonly performed and safest surgical procedures worldwide. At Prism Healthcure, we use advanced phacoemulsification and femtosecond laser-assisted techniques to remove the clouded natural lens and replace it with a premium intraocular lens (IOL).',
    duration: '15-20 minutes',
    recovery: '24-48 hours',
    anesthesia: 'Topical (eye drops)',
    successRate: '99.5%',
    costRange: '₹15,000 – ₹1,20,000',
    symptoms: ['Blurry or cloudy vision','Difficulty seeing at night','Sensitivity to light and glare','Seeing halos around lights','Fading or yellowing of colors','Double vision in one eye','Frequent prescription changes'],
    types: [
      { name: 'Phacoemulsification (Phaco)', desc: 'Most common modern technique using ultrasound to break up the lens through a tiny 2.2mm incision.' },
      { name: 'Femtosecond Laser-Assisted (FLACS)', desc: 'Computer-guided laser creates precise incisions for enhanced accuracy and faster healing.' },
      { name: 'Micro-Incision (MICS)', desc: 'Ultra-small incision of less than 1.8mm for minimal tissue disruption and faster recovery.' },
    ],
    lensOptions: [
      { name: 'Monofocal IOL', desc: 'Clear vision at one distance (near or far). Most affordable option.' },
      { name: 'Multifocal IOL', desc: 'Corrects both near and far vision, reducing need for glasses.' },
      { name: 'Toric IOL', desc: 'Corrects astigmatism along with cataracts for sharper vision.' },
      { name: 'Extended Depth of Focus (EDOF)', desc: 'Provides continuous range of vision from intermediate to far.' },
    ],
    preparation: ['Complete eye examination and biometry','Discuss IOL options with your surgeon','Stop blood thinners if advised','Arrange transportation for surgery day','Fast for 4-6 hours before surgery'],
    aftercare: ['Use prescribed eye drops as directed','Wear protective eye shield while sleeping for 1 week','Avoid rubbing your eyes','No heavy lifting for 2 weeks','Attend follow-up appointments on Day 1, Week 1, and Month 1'],
    faqs: [
      { q: 'Is cataract surgery painful?', a: 'No. The procedure is virtually painless. Numbing eye drops are used, and most patients feel only mild pressure.' },
      { q: 'Can cataracts come back after surgery?', a: 'No. Once removed, cataracts cannot return. In some cases, the lens capsule may become cloudy (posterior capsule opacification), which is easily treated with a quick YAG laser procedure.' },
      { q: 'When can I resume normal activities?', a: 'Most patients resume light activities within 24-48 hours. Full recovery takes about 4-6 weeks.' },
      { q: 'Will I need glasses after cataract surgery?', a: 'It depends on the IOL chosen. Multifocal and EDOF lenses can significantly reduce or eliminate the need for glasses.' },
    ],
    hi: {
      title: 'मोतियाबिंद सर्जरी',
      subtitle: 'क्रिस्टल जैसी स्पष्ट दृष्टि प्राप्त करें',
      overview: 'मोतियाबिंद सर्जरी दुनिया भर में सबसे अधिक की जाने वाली और सबसे सुरक्षित सर्जिकल प्रक्रियाओं में से एक है। प्रिज्म हेल्थक्योर में, हम धुंधले प्राकृतिक लेंस को हटाने और इसे प्रीमियम इंट्राओकुलर लेंस (IOL) से बदलने के लिए उन्नत फेकोइमल्सीफिकेशन और फेम्टोसेकंड लेजर-असिस्टेड तकनीकों का उपयोग करते हैं।',
      duration: '15-20 मिनट',
      recovery: '24-48 घंटे',
      anesthesia: 'स्थानीय (आई ड्रॉप्स)',
      successRate: '99.5%',
      costRange: '₹15,000 – ₹1,20,000',
      symptoms: ['धुंधली या बादली दृष्टि','रात में देखने में कठिनाई','प्रकाश और चकाचौंध के प्रति संवेदनशीलता','रोशनी के चारों ओर प्रभामंडल देखना','रंगों का फीका पड़ना या पीला पड़ना','एक आँख में दोहरी दृष्टि','लगातार चश्मे का नंबर बदलना'],
      types: [
        { name: 'फेकोइमल्सीफिकेशन (Phaco)', desc: 'एक छोटे 2.2 मिमी चीरे के माध्यम से लेंस को तोड़ने के लिए अल्ट्रासाउंड का उपयोग करने वाली सबसे आम आधुनिक तकनीक।' },
        { name: 'फेम्टोसेकंड लेजर-असिस्टेड (FLACS)', desc: 'कंप्यूटर-निर्देशित लेजर उन्नत सटीकता और तेजी से उपचार के लिए सटीक चीरे बनाता है।' },
        { name: 'माइक्रो-इंसिजन (MICS)', desc: 'न्यूनतम ऊतक व्यवधान और तेजी से रिकवरी के लिए 1.8 मिमी से कम का अल्ट्रा-छोटा चीरा।' },
      ],
      lensOptions: [
        { name: 'मोनोफोकल आईओएल', desc: 'एक दूरी (पास या दूर) पर स्पष्ट दृष्टि। सबसे किफायती विकल्प।' },
        { name: 'मल्टीफोकल आईओएल', desc: 'पास और दूर दोनों की दृष्टि को ठीक करता है, जिससे चश्मे की आवश्यकता कम हो जाती है।' },
        { name: 'टोरिक आईओएल', desc: 'तेज दृष्टि के लिए मोतियाबिंद के साथ-साथ दृष्टिवैषम्य (astigmatism) को ठीक करता है।' },
        { name: 'एक्सटेंडेड डेप्थ ऑफ फोकस (EDOF)', desc: 'मध्यम से दूर तक दृष्टि की निरंतर सीमा प्रदान करता है।' },
      ],
      preparation: ['संपूर्ण नेत्र परीक्षण और बायोमेट्री','अपने सर्जन के साथ आईओएल विकल्पों पर चर्चा करें','सलाह दिए जाने पर रक्त पतला करने वाली दवाएं बंद करें','सर्जरी के दिन परिवहन की व्यवस्था करें','सर्जरी से 4-6 घंटे पहले उपवास रखें'],
      aftercare: ['निर्देशानुसार निर्धारित आई ड्रॉप्स का उपयोग करें','सोते समय 1 सप्ताह तक सुरक्षात्मक आई शील्ड पहनें','अपनी आँखों को रगड़ने से बचें','2 सप्ताह तक भारी वजन न उठाएं','दिन 1, सप्ताह 1 और महीने 1 पर फॉलो-अप अपॉइंटमेंट लें'],
      faqs: [
        { q: 'क्या मोतियाबिंद की सर्जरी दर्दनाक है?', a: 'नहीं। प्रक्रिया वस्तुतः दर्द रहित है। सुन्न करने वाली आई ड्रॉप्स का उपयोग किया जाता है, और अधिकांश रोगियों को केवल हल्का दबाव महसूस होता है।' },
        { q: 'क्या सर्जरी के बाद मोतियाबिंद वापस आ सकता है?', a: 'नहीं। एक बार हटा दिए जाने के बाद, मोतियाबिंद वापस नहीं आ सकता है।' },
        { q: 'मैं सामान्य गतिविधियाँ कब शुरू कर सकता हूँ?', a: 'अधिकांश रोगी 24-48 घंटों के भीतर हल्की गतिविधियाँ शुरू कर देते हैं।' },
      ],
    }
  },
  lasik: {
    title: 'LASIK & Refractive Surgery',
    subtitle: 'Freedom from Glasses & Contacts',
    heroImage: 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&q=80&w=1200',
    overview: 'LASIK (Laser-Assisted In Situ Keratomileusis) is a revolutionary refractive surgery that permanently corrects myopia, hyperopia, and astigmatism. Our bladeless, all-laser LASIK uses femtosecond technology for unparalleled precision and safety.',
    duration: '10-15 minutes (both eyes)',
    recovery: 'Next day',
    anesthesia: 'Topical (eye drops)',
    successRate: '99.2%',
    costRange: '₹25,000 – ₹1,00,000',
    symptoms: ['Dependence on glasses or contact lenses','Myopia (nearsightedness)','Hyperopia (farsightedness)','Astigmatism','Desire for spectacle-free lifestyle'],
    types: [
      { name: 'Bladeless LASIK (Femto-LASIK)', desc: 'All-laser procedure creating a precise corneal flap with femtosecond laser.' },
      { name: 'PRK/TransPRK', desc: 'Surface ablation technique ideal for patients with thin corneas.' },
      { name: 'SMILE (Small Incision Lenticule Extraction)', desc: 'Flapless, minimally invasive procedure through a tiny 2mm incision.' },
      { name: 'ICL (Implantable Collamer Lens)', desc: 'For high prescriptions where LASIK is not suitable. A biocompatible lens is implanted inside the eye.' },
    ],
    lensOptions: [],
    preparation: ['Stop wearing contact lenses 1-2 weeks before','Complete comprehensive eye evaluation','Corneal topography and pachymetry mapping','Ensure stable prescription for at least 1 year','No eye makeup on surgery day'],
    aftercare: ['Use prescribed lubricating and antibiotic drops','Wear protective sunglasses outdoors','Avoid swimming and dusty environments for 2 weeks','No eye rubbing for 1 month','Follow-up visits at Day 1, Week 1, Month 1, and Month 3'],
    faqs: [
      { q: 'Am I a good candidate for LASIK?', a: 'Ideal candidates are 18+ years old, have a stable prescription for at least 1 year, adequate corneal thickness, and no active eye diseases.' },
      { q: 'Is LASIK permanent?', a: 'Yes. LASIK permanently reshapes the cornea. However, age-related changes like presbyopia may still occur after 40.' },
      { q: 'What if I blink during the procedure?', a: 'A gentle lid speculum holds your eyelids open during the procedure. Eye tracking technology adjusts for any micro-movements.' },
    ],
    hi: {
      title: 'लैसिक और अपवर्तक सर्जरी',
      subtitle: 'चश्मे और कॉन्टैक्ट लेंस से मुक्ति',
      overview: 'लैसिक (LASIK) एक क्रांतिकारी अपवर्तक सर्जरी है जो मायोपिया, हाइपरोपिया और दृष्टिवैषम्य को स्थायी रूप से ठीक करती है। हमारी ब्लेडलेस, ऑल-लेजर लैसिक अद्वितीय सटीकता और सुरक्षा के लिए फेम्टोसेकंड तकनीक का उपयोग करती है।',
      duration: '10-15 मिनट (दोनों आँखें)',
      recovery: 'अगले दिन',
      anesthesia: 'स्थानीय (आई ड्रॉप्स)',
      successRate: '99.2%',
      costRange: '₹25,000 – ₹1,00,000',
      symptoms: ['चश्मे या कॉन्टैक्ट लेंस पर निर्भरता','मायोपिया (निकट दृष्टि दोष)','हाइपरोपिया (दूर दृष्टि दोष)','दृष्टिवैषम्य (Astigmatism)','चश्मा मुक्त जीवनशैली की इच्छा'],
      types: [
        { name: 'ब्लेडलेस लैसिक (Femto-LASIK)', desc: 'फेम्टोसेकंड लेजर के साथ एक सटीक कॉर्नियल फ्लैप बनाने वाली ऑल-लेजर प्रक्रिया।' },
        { name: 'PRK/TransPRK', desc: 'पतले कॉर्निया वाले रोगियों के लिए आदर्श सतह पृथक तकनीक।' },
        { name: 'SMILE', desc: 'एक छोटे 2 मिमी चीरे के माध्यम से फ्लैपलेस, न्यूनतम आक्रामक प्रक्रिया।' },
        { name: 'ICL (इम्प्लांटेबल कोलामेर लेंस)', desc: 'उच्च नंबर के लिए जहाँ लैसिक उपयुक्त नहीं है। आँख के अंदर एक बायोकंपैटिबल लेंस लगाया जाता है।' },
      ],
      lensOptions: [],
      preparation: ['1-2 सप्ताह पहले कॉन्टैक्ट लेंस पहनना बंद करें','व्यापक नेत्र मूल्यांकन पूरा करें','कॉर्नियल टोपोग्राफी और पैकीमेट्री मैपिंग','कम से कम 1 वर्ष तक स्थिर चश्मे का नंबर सुनिश्चित करें','सर्जरी के दिन कोई आँख का मेकअप न करें'],
      aftercare: ['निर्धारित लुब्रिकेटिंग और एंटीबायोटिक ड्रॉप्स का उपयोग करें','बाहर सुरक्षात्मक धूप का चश्मा पहनें','2 सप्ताह तक तैराकी और धूल भरे वातावरण से बचें','1 महीने तक आँख न रगड़ें','फॉलो-अप विज़िट दिन 1, सप्ताह 1, महीने 1 और महीने 3 पर करें'],
      faqs: [
        { q: 'क्या मैं लैसिक के लिए एक अच्छा उम्मीदवार हूँ?', a: 'आदर्श उम्मीदवार 18+ वर्ष के होते हैं, कम से कम 1 वर्ष से स्थिर नंबर होता है, और कोई सक्रिय नेत्र रोग नहीं होता है।' },
        { q: 'क्या लैसिक स्थायी है?', a: 'हाँ। लैसिक कॉर्निया को स्थायी रूप से नया आकार देता है।' },
      ],
    }
  },
  retina: {
    title: 'Retina Care',
    subtitle: 'Protecting Your Vision from Within',
    heroImage: 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?auto=format&fit=crop&q=80&w=1200',
    overview: 'The retina is the light-sensitive tissue lining the back of your eye, essential for vision. Our retina specialists diagnose and treat conditions like diabetic retinopathy, macular degeneration, retinal detachment, and vitreous disorders using cutting-edge imaging and surgical techniques.',
    duration: '30-90 minutes',
    recovery: '2-6 weeks',
    anesthesia: 'Local/General',
    successRate: '95%+',
    costRange: '₹20,000 – ₹2,00,000',
    symptoms: ['Sudden increase in floaters','Flashes of light','Shadow or curtain over vision','Distorted or wavy vision','Gradual loss of central vision','Dark spots in vision'],
    types: [
      { name: 'Anti-VEGF Injections', desc: 'Intravitreal injections to stop abnormal blood vessel growth in wet AMD and diabetic retinopathy.' },
      { name: 'Retinal Laser (Photocoagulation)', desc: 'Laser treatment to seal leaking blood vessels or create barriers around retinal tears.' },
      { name: 'Vitrectomy', desc: 'Microsurgery to remove vitreous gel and repair detached retina, macular holes, or epiretinal membranes.' },
      { name: 'Scleral Buckling', desc: 'External silicone band placed around the eye to push the wall toward the detached retina.' },
    ],
    lensOptions: [],
    preparation: ['Dilated fundus examination','OCT (Optical Coherence Tomography) scan','Fluorescein angiography if needed','Blood sugar control for diabetic patients','Arrange for someone to drive you home'],
    aftercare: ['Maintain specific head positioning if gas bubble is used','Use prescribed eye drops diligently','Avoid air travel if gas bubble is present','Regular follow-up imaging scans','Monitor for any vision changes and report immediately'],
    faqs: [
      { q: 'Can diabetic retinopathy be reversed?', a: 'Early stages can be managed effectively with blood sugar control and treatment. Advanced stages can be treated to prevent further vision loss, but lost vision may not be fully recoverable.' },
      { q: 'How urgent is retinal detachment?', a: 'Retinal detachment is a medical emergency. Seek immediate treatment — delay can lead to permanent vision loss.' },
    ],
    hi: {
      title: 'रेटिना देखभाल',
      subtitle: 'भीतर से आपकी दृष्टि की रक्षा करना',
      overview: 'रेटिना आपकी आँख के पीछे स्थित प्रकाश-संवेदनशील ऊतक है, जो दृष्टि के लिए आवश्यक है। हमारे रेटिना विशेषज्ञ अत्याधुनिक इमेजिंग और सर्जिकल तकनीकों का उपयोग करके डायबिटिक रेटिनोपैथी, मैकुलर डिजनरेशन, रेटिनल डिटैचमेंट और विट्रियस विकारों का निदान और उपचार करते हैं।',
      duration: '30-90 मिनट',
      recovery: '2-6 सप्ताह',
      anesthesia: 'स्थानीय/सामान्य',
      successRate: '95%+',
      costRange: '₹20,000 – ₹2,00,000',
      symptoms: ['फ्लोटर्स में अचानक वृद्धि','प्रकाश की चमक','दृष्टि पर छाया या पर्दा','विकृत या लहरदार दृष्टि','केंद्रीय दृष्टि का क्रमिक नुकसान','दृष्टि में काले धब्बे'],
      types: [
        { name: 'एंटी-वीईजीएफ इंजेक्शन', desc: 'गीले एएमडी और डायबिटिक रेटिनोपैथी में असामान्य रक्त वाहिका वृद्धि को रोकने के लिए इंट्राविट्रियल इंजेक्शन।' },
        { name: 'रेटिनल लेजर', desc: 'रिसने वाली रक्त वाहिकाओं को सील करने या रेटिनल आँसू के चारों ओर बाधाएं बनाने के लिए लेजर उपचार।' },
        { name: 'विट्रेक्टोमी', desc: 'विट्रियस जेल को हटाने और फटे रेटिना, मैकुलर होल या एपिरेटिनल झिल्ली की मरम्मत के लिए माइक्रोसर्जरी।' },
      ],
      lensOptions: [],
      preparation: ['विस्तृत फंडस परीक्षा','OCT स्कैन','फ्लोरेसिन एंजियोग्राफी (यदि आवश्यक हो)','मधुमेह रोगियों के लिए रक्त शर्करा नियंत्रण','वापस ले जाने के लिए किसी की व्यवस्था करें'],
      aftercare: ['विशिष्ट सिर की स्थिति बनाए रखें (यदि गैस बबल का उपयोग किया जाता है)','निर्धारित आई ड्रॉप्स का सावधानीपूर्वक उपयोग करें','गैस बबल मौजूद होने पर हवाई यात्रा से बचें','नियमित फॉलो-अप इमेजिंग स्कैन','दृष्टि परिवर्तन की निगरानी करें'],
      faqs: [
        { q: 'क्या डायबिटिक रेटिनोपैथी को ठीक किया जा सकता है?', a: 'शुरुआती चरणों को प्रभावी ढंग से प्रबंधित किया जा सकता है। उन्नत चरणों का इलाज आगे की दृष्टि हानि को रोकने के लिए किया जा सकता है।' },
        { q: 'रेटिनल डिटैचमेंट कितना जरूरी है?', a: 'रेटिनल डिटैचमेंट एक मेडिकल इमरजेंसी है। तुरंत उपचार लें।' },
      ],
    }
  },
  glaucoma: {
    title: 'Glaucoma Treatment',
    subtitle: 'Preserving Vision Before It\'s Too Late',
    heroImage: 'https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?auto=format&fit=crop&q=80&w=1200',
    overview: 'Glaucoma is a group of eye conditions that damage the optic nerve, often due to elevated intraocular pressure (IOP). Known as the "silent thief of sight," it progresses without symptoms until significant vision is lost. Early detection through regular screening is crucial.',
    duration: '15-45 minutes',
    recovery: '1-4 weeks',
    anesthesia: 'Topical/Local',
    successRate: '90%+',
    costRange: '₹10,000 – ₹80,000',
    symptoms: ['Gradual loss of peripheral (side) vision','Tunnel vision in advanced stages','Eye pain or redness (acute angle-closure)','Halos around lights','Headaches with eye strain','Often NO symptoms in early stages'],
    types: [
      { name: 'Medications (Eye Drops)', desc: 'First-line treatment to reduce IOP through prostaglandin analogs, beta-blockers, or carbonic anhydrase inhibitors.' },
      { name: 'Selective Laser Trabeculoplasty (SLT)', desc: 'Gentle laser applied to the drainage angle to improve fluid outflow. Repeatable and safe.' },
      { name: 'Trabeculectomy', desc: 'Surgical creation of a new drainage channel to lower eye pressure when medications and laser are insufficient.' },
      { name: 'MIGS (Micro-Invasive Glaucoma Surgery)', desc: 'Minimally invasive procedures using tiny stents or devices for safer, faster recovery.' },
    ],
    lensOptions: [],
    preparation: ['Comprehensive glaucoma evaluation','Visual field test (perimetry)','OCT of optic nerve head','Gonioscopy to examine drainage angle','Review of current medications'],
    aftercare: ['Continue prescribed eye drops as directed','Avoid strenuous activity for 2 weeks after surgery','Attend regular IOP monitoring appointments','Never stop glaucoma medications without consulting your doctor','Annual visual field testing'],
    faqs: [
      { q: 'Can glaucoma be cured?', a: 'Glaucoma cannot be cured, but it can be effectively managed. Treatment focuses on lowering eye pressure to prevent further optic nerve damage.' },
      { q: 'Who is at risk for glaucoma?', a: 'Risk factors include age over 40, family history, high eye pressure, diabetes, high myopia, and previous eye injuries.' },
    ],
    hi: {
      title: 'ग्लूकोमा उपचार',
      subtitle: 'देर होने से पहले दृष्टि को सुरक्षित रखना',
      overview: 'ग्लूकोमा नेत्र स्थितियों का एक समूह है जो ऑप्टिक तंत्रिका को नुकसान पहुँचाता है, अक्सर बढ़े हुए इंट्राओकुलर दबाव (IOP) के कारण। इसे "दृष्टि का चुपचाप चोर" कहा जाता है, यह महत्वपूर्ण दृष्टि खो जाने तक बिना किसी लक्षण के आगे बढ़ता है।',
      duration: '15-45 मिनट',
      recovery: '1-4 सप्ताह',
      anesthesia: 'स्थानीय',
      successRate: '90%+',
      costRange: '₹10,000 – ₹80,000',
      symptoms: ['परिधीय (साइड) दृष्टि का क्रमिक नुकसान','उन्नत चरणों में टनल विजन','आँख में दर्द या लालिमा','रोशनी के चारों ओर प्रभामंडल','आँखों के तनाव के साथ सिरदर्द','अक्सर शुरुआती चरणों में कोई लक्षण नहीं'],
      types: [
        { name: 'दवाएं (आई ड्रॉप्स)', desc: 'IOP को कम करने के लिए पहली पंक्ति का उपचार।' },
        { name: 'चयनात्मक लेजर ट्रैबेकुलोप्लास्टी (SLT)', desc: 'तरल पदार्थ के बहिर्वाह को बेहतर बनाने के लिए जल निकासी कोण पर लगाया गया हल्का लेजर।' },
        { name: 'ट्रैबेकुलेक्टोमी', desc: 'आँख के दबाव को कम करने के लिए एक नए जल निकासी चैनल का सर्जिकल निर्माण।' },
      ],
      lensOptions: [],
      preparation: ['व्यापक ग्लूकोमा मूल्यांकन','विजुअल फील्ड टेस्ट (पेरिमेट्री)','ऑप्टिक नर्व हेड का OCT','ड्रैनेज एंगल की जांच के लिए गोनियोस्कोपी','वर्तमान दवाओं की समीक्षा'],
      aftercare: ['निर्धारित आई ड्रॉप्स जारी रखें','सर्जरी के 2 सप्ताह बाद तक कड़ी मेहनत से बचें','नियमित IOP निगरानी नियुक्तियों में भाग लें','डॉक्टर की सलाह के बिना ग्लूकोमा की दवाएं कभी बंद न करें','वार्षिक विजुअल फील्ड परीक्षण'],
      faqs: [
        { q: 'क्या ग्लूकोमा को ठीक किया जा सकता है?', a: 'ग्लूकोमा को ठीक नहीं किया जा सकता है, लेकिन इसे प्रभावी ढंग से प्रबंधित किया जा सकता है।' },
      ],
    }
  },
  cornea: {
    title: 'Cornea Services',
    subtitle: 'Clarity Starts at the Surface',
    heroImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=1200',
    overview: 'The cornea is the clear, dome-shaped front surface of your eye that plays a crucial role in focusing vision. Our cornea specialists treat conditions ranging from infections and keratoconus to corneal scarring, offering advanced procedures including corneal transplants.',
    duration: '30-90 minutes',
    recovery: '3-12 months',
    anesthesia: 'Local/General',
    successRate: '90%+',
    costRange: '₹30,000 – ₹2,50,000',
    symptoms: ['Blurred or distorted vision','Eye pain or sensitivity to light','Corneal opacity or scarring','Progressive thinning of cornea','Severe dry eyes','Recurrent corneal erosions'],
    types: [
      { name: 'Penetrating Keratoplasty (PK)', desc: 'Full-thickness corneal transplant replacing the entire damaged cornea with a donor cornea.' },
      { name: 'DALK (Deep Anterior Lamellar Keratoplasty)', desc: 'Partial-thickness transplant preserving the patient\'s inner corneal layer, reducing rejection risk.' },
      { name: 'DSEK/DMEK', desc: 'Endothelial keratoplasty replacing only the innermost corneal layer for conditions like Fuchs dystrophy.' },
      { name: 'Corneal Collagen Cross-Linking (C3R)', desc: 'UV-riboflavin treatment to strengthen and stabilize the cornea in keratoconus.' },
    ],
    lensOptions: [],
    preparation: ['Detailed corneal evaluation and topography','Pachymetry and specular microscopy','Blood tests and medical clearance','Discussion of donor tissue availability','Understanding realistic recovery expectations'],
    aftercare: ['Strict adherence to anti-rejection eye drops','Protect eye from injury','Regular follow-up for graft monitoring','Suture removal at scheduled intervals','Vision may continue improving for up to 12 months'],
    faqs: [
      { q: 'How long does a corneal transplant last?', a: 'A successful corneal transplant can last many years to decades with proper care and medication compliance.' },
      { q: 'What is keratoconus?', a: 'Keratoconus is a progressive condition where the cornea thins and bulges into a cone shape, causing distorted vision. C3R can halt its progression.' },
    ],
    hi: {
      title: 'कॉर्निया सेवाएं',
      subtitle: 'स्पष्टता सतह से शुरू होती है',
      overview: 'कॉर्निया आपकी आँख की स्पष्ट, गुंबद के आकार की सामने की सतह है जो दृष्टि को केंद्रित करने में महत्वपूर्ण भूमिका निभाती है। हमारे कॉर्निया विशेषज्ञ संक्रमण और केराटोकोनस से लेकर कॉर्नियल स्कारिंग तक की स्थितियों का इलाज करते हैं।',
      duration: '30-90 मिनट',
      recovery: '3-12 महीने',
      anesthesia: 'स्थानीय/सामान्य',
      successRate: '90%+',
      costRange: '₹30,000 – ₹2,50,000',
      symptoms: ['धुंधली या विकृत दृष्टि','आँख में दर्द या प्रकाश के प्रति संवेदनशीलता','कॉर्नियल अपारदर्शिता या स्कारिंग','कॉर्निया का क्रमिक पतला होना','गंभीर सूखी आँखें'],
      types: [
        { name: 'पेनेट्रेटिंग केराटोप्लास्टी (PK)', desc: 'पूरी क्षतिग्रस्त कॉर्निया को डोनर कॉर्निया से बदलने वाला फुल-थिकनेस कॉर्नियल ट्रांसप्लांट।' },
        { name: 'DALK', desc: 'रिजेक्शन के जोखिम को कम करने वाला पार्शियल-थिकनेस ट्रांसप्लांट।' },
        { name: 'C3R', desc: 'केराटोकोनस में कॉर्निया को मजबूत और स्थिर करने के लिए UV-राइबोफ्लेविन उपचार।' },
      ],
      lensOptions: [],
      preparation: ['विस्तृत कॉर्नियल मूल्यांकन और टोपोग्राफी','पैकिमेट्री और स्पेक्युलर माइक्रोस्कोपी','रक्त परीक्षण और मेडिकल क्लीयरेंस','डोनर टिश्यू की उपलब्धता पर चर्चा'],
      aftercare: ['एंटी-रिजेक्शन आई ड्रॉप्स का सख्त पालन','आँख को चोट से बचाएं','ग्राफ्ट निगरानी के लिए नियमित फॉलो-अप','निर्धारित अंतराल पर टांके हटाना'],
      faqs: [
        { q: 'कॉर्नियल ट्रांसप्लांट कितने समय तक चलता है?', a: 'उचित देखभाल के साथ एक सफल कॉर्नियल ट्रांसप्लांट कई वर्षों से दशकों तक चल सकता है।' },
      ],
    }
  },
  pediatric: {
    title: 'Pediatric Eye Care',
    subtitle: 'Gentle Expert Care for Little Eyes',
    heroImage: 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?auto=format&fit=crop&q=80&w=1200',
    overview: 'Children\'s eyes are still developing, making early detection and treatment of vision problems critical. Our pediatric ophthalmologists specialize in diagnosing and treating conditions like squint (strabismus), lazy eye (amblyopia), congenital cataracts, and refractive errors in a child-friendly environment.',
    duration: 'Varies by procedure',
    recovery: 'Varies',
    anesthesia: 'General (for surgery)',
    successRate: '95%+',
    costRange: '₹5,000 – ₹1,50,000',
    symptoms: ['Misaligned or crossed eyes','Squinting or closing one eye','Tilting head to see','Sitting too close to TV','Difficulty reading or poor school performance','Excessive tearing or eye rubbing','White reflex in pupil'],
    types: [
      { name: 'Squint (Strabismus) Surgery', desc: 'Precise adjustment of eye muscles to align the eyes, often performed under general anesthesia.' },
      { name: 'Amblyopia (Lazy Eye) Treatment', desc: 'Patching therapy, atropine drops, or vision therapy to strengthen the weaker eye.' },
      { name: 'Pediatric Cataract Surgery', desc: 'Removal of congenital or developmental cataracts with or without IOL implantation.' },
      { name: 'ROP Screening & Treatment', desc: 'Screening and laser treatment for Retinopathy of Prematurity in premature infants.' },
    ],
    lensOptions: [],
    preparation: ['Child-friendly comprehensive eye exam','Cycloplegic refraction for accurate measurement','Assessment of binocular vision','Pre-anesthetic evaluation for surgery cases','Reassure the child with age-appropriate explanations'],
    aftercare: ['Follow patching or medication schedule strictly','Regular follow-up visits as vision develops','Monitor for recurrence of squint','Encourage outdoor activities for myopia prevention','Annual comprehensive eye exams throughout childhood'],
    faqs: [
      { q: 'At what age should my child first see an eye doctor?', a: 'The first eye screening should be at 6 months, then at age 3, and before starting school. Children with risk factors should be examined earlier.' },
      { q: 'Will my child outgrow crossed eyes?', a: 'True strabismus does not resolve on its own and requires treatment. Early intervention gives the best outcomes. Pseudo-strabismus (flat nasal bridge) is common in infants and resolves naturally.' },
    ],
    hi: {
      title: 'पीडियाट्रिक नेत्र देखभाल',
      subtitle: 'नन्हीं आँखों के लिए कोमल विशेषज्ञ देखभाल',
      overview: 'बच्चों की आँखें अभी भी विकसित हो रही हैं, जिससे दृष्टि समस्याओं का जल्दी पता लगाना और उपचार करना महत्वपूर्ण हो जाता है। हमारे पीडियाट्रिक नेत्र विशेषज्ञ बाल-सुलभ वातावरण में भेंगापन (squint), आलसी आँख (amblyopia), और जन्मजात मोतियाबिंद जैसी स्थितियों के निदान और उपचार में विशेषज्ञ हैं।',
      duration: 'प्रक्रिया के अनुसार',
      recovery: 'परिवर्तनशील',
      anesthesia: 'सामान्य (सर्जरी के लिए)',
      successRate: '95%+',
      costRange: '₹5,000 – ₹1,50,000',
      symptoms: ['तिरछी या घूमी हुई आँखें','एक आँख को भींचना या बंद करना','देखने के लिए सिर झुकाना','टीवी के बहुत पास बैठना','पढ़ने में कठिनाई या खराब स्कूली प्रदर्शन','पुतली में सफेद रिफ्लेक्स'],
      types: [
        { name: 'भेंगापन (Squint) सर्जरी', desc: 'आँखों को संरेखित करने के लिए आँख की मांसपेशियों का सटीक समायोजन।' },
        { name: 'आलसी आँख (Amblyopia) उपचार', desc: 'कमजोर आँख को मजबूत करने के लिए पैचिंग थेरेपी या विजन थेरेपी।' },
        { name: 'पीडियाट्रिक मोतियाबिंद सर्जरी', desc: 'आईओएल प्रत्यारोपण के साथ या बिना जन्मजात मोतियाबिंद को हटाना।' },
      ],
      lensOptions: [],
      preparation: ['बाल-सुलभ व्यापक नेत्र परीक्षण','सटीक माप के लिए साइक्लोप्लेजिक अपवर्तन','द्विनेत्री दृष्टि का आकलन','सर्जरी के मामलों के लिए प्री-एनेस्थेटिक मूल्यांकन'],
      aftercare: ['पैचिंग या दवा शेड्यूल का सख्ती से पालन करें','दृष्टि विकसित होने पर नियमित फॉलो-अप विज़िट','भेंगापन की पुनरावृत्ति की निगरानी करें','मायोपिया की रोकथाम के लिए बाहरी गतिविधियों को प्रोत्साहित करें'],
      faqs: [
        { q: 'मेरे बच्चे को पहली बार आँख के डॉक्टर को कब दिखाना चाहिए?', a: 'पहली नेत्र जांच 6 महीने में, फिर 3 साल की उम्र में और स्कूल शुरू करने से पहले होनी चाहिए।' },
      ],
    }
  },
};

export type TreatmentSlug = keyof typeof treatments;
export const treatmentSlugs = Object.keys(treatments) as TreatmentSlug[];
