export const treatments = {
  cataract: {
    title: 'Cataract Surgery',
    subtitle: 'Restore Crystal-Clear Vision',
    heroImage: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&q=80&w=1200',
    overview: 'Cataract surgery is one of the most commonly performed and safest surgical procedures worldwide. At Prism Healthcure, we use advanced phacoemulsification and femtosecond laser-assisted techniques to remove the clouded natural lens and replace it with a premium intraocular lens (IOL).',
    duration: '15-20 minutes',
    recovery: '24-48 hours',
    anesthesia: 'Topical (eye drops)',
    successRate: '99.5%',
    costRange: '₹15,000 – ₹1,20,000',
    symptoms: ['Blurry or cloudy vision','Difficulty seeing at night','Sensitivity to light and glare','Seeing halos around lights','Fading or yellowing of colors','Double vision in one eye','Frequent prescription changes'],
    types: [
      { name: 'Phacoemulsification (Phaco)', desc: 'Most common modern technique using ultrasound to break up the lens through a tiny 2.2mm incision.' },
      { name: 'Femtosecond Laser-Assisted (FLACS)', desc: 'Computer-guided laser creates precise incisions for enhanced accuracy and faster healing.' },
      { name: 'Micro-Incision (MICS)', desc: 'Ultra-small incision of less than 1.8mm for minimal tissue disruption and faster recovery.' },
    ],
    lensOptions: [
      { name: 'Monofocal IOL', desc: 'Clear vision at one distance (near or far). Most affordable option.' },
      { name: 'Multifocal IOL', desc: 'Corrects both near and far vision, reducing need for glasses.' },
      { name: 'Toric IOL', desc: 'Corrects astigmatism along with cataracts for sharper vision.' },
      { name: 'Extended Depth of Focus (EDOF)', desc: 'Provides continuous range of vision from intermediate to far.' },
    ],
    preparation: ['Complete eye examination and biometry','Discuss IOL options with your surgeon','Stop blood thinners if advised','Arrange transportation for surgery day','Fast for 4-6 hours before surgery'],
    aftercare: ['Use prescribed eye drops as directed','Wear protective eye shield while sleeping for 1 week','Avoid rubbing your eyes','No heavy lifting for 2 weeks','Attend follow-up appointments on Day 1, Week 1, and Month 1'],
    faqs: [
      { q: 'Is cataract surgery painful?', a: 'No. The procedure is virtually painless. Numbing eye drops are used, and most patients feel only mild pressure.' },
      { q: 'Can cataracts come back after surgery?', a: 'No. Once removed, cataracts cannot return. In some cases, the lens capsule may become cloudy (posterior capsule opacification), which is easily treated with a quick YAG laser procedure.' },
      { q: 'When can I resume normal activities?', a: 'Most patients resume light activities within 24-48 hours. Full recovery takes about 4-6 weeks.' },
      { q: 'Will I need glasses after cataract surgery?', a: 'It depends on the IOL chosen. Multifocal and EDOF lenses can significantly reduce or eliminate the need for glasses.' },
    ],
  },
  lasik: {
    title: 'LASIK & Refractive Surgery',
    subtitle: 'Freedom from Glasses & Contacts',
    heroImage: 'https://images.unsplash.com/photo-1581595220892-b0739db3ba8c?auto=format&fit=crop&q=80&w=1200',
    overview: 'LASIK (Laser-Assisted In Situ Keratomileusis) is a revolutionary refractive surgery that permanently corrects myopia, hyperopia, and astigmatism. Our bladeless, all-laser LASIK uses femtosecond technology for unparalleled precision and safety.',
    duration: '10-15 minutes (both eyes)',
    recovery: 'Next day',
    anesthesia: 'Topical (eye drops)',
    successRate: '99.2%',
    costRange: '₹25,000 – ₹1,00,000',
    symptoms: ['Dependence on glasses or contact lenses','Myopia (nearsightedness)','Hyperopia (farsightedness)','Astigmatism','Desire for spectacle-free lifestyle'],
    types: [
      { name: 'Bladeless LASIK (Femto-LASIK)', desc: 'All-laser procedure creating a precise corneal flap with femtosecond laser.' },
      { name: 'PRK/TransPRK', desc: 'Surface ablation technique ideal for patients with thin corneas.' },
      { name: 'SMILE (Small Incision Lenticule Extraction)', desc: 'Flapless, minimally invasive procedure through a tiny 2mm incision.' },
      { name: 'ICL (Implantable Collamer Lens)', desc: 'For high prescriptions where LASIK is not suitable. A biocompatible lens is implanted inside the eye.' },
    ],
    lensOptions: [],
    preparation: ['Stop wearing contact lenses 1-2 weeks before','Complete comprehensive eye evaluation','Corneal topography and pachymetry mapping','Ensure stable prescription for at least 1 year','No eye makeup on surgery day'],
    aftercare: ['Use prescribed lubricating and antibiotic drops','Wear protective sunglasses outdoors','Avoid swimming and dusty environments for 2 weeks','No eye rubbing for 1 month','Follow-up visits at Day 1, Week 1, Month 1, and Month 3'],
    faqs: [
      { q: 'Am I a good candidate for LASIK?', a: 'Ideal candidates are 18+ years old, have a stable prescription for at least 1 year, adequate corneal thickness, and no active eye diseases.' },
      { q: 'Is LASIK permanent?', a: 'Yes. LASIK permanently reshapes the cornea. However, age-related changes like presbyopia may still occur after 40.' },
      { q: 'What if I blink during the procedure?', a: 'A gentle lid speculum holds your eyelids open during the procedure. Eye tracking technology adjusts for any micro-movements.' },
    ],
  },
  retina: {
    title: 'Retina Care',
    subtitle: 'Protecting Your Vision from Within',
    heroImage: 'https://images.unsplash.com/photo-1559757175-7cb057fba93c?auto=format&fit=crop&q=80&w=1200',
    overview: 'The retina is the light-sensitive tissue lining the back of your eye, essential for vision. Our retina specialists diagnose and treat conditions like diabetic retinopathy, macular degeneration, retinal detachment, and vitreous disorders using cutting-edge imaging and surgical techniques.',
    duration: '30-90 minutes',
    recovery: '2-6 weeks',
    anesthesia: 'Local/General',
    successRate: '95%+',
    costRange: '₹20,000 – ₹2,00,000',
    symptoms: ['Sudden increase in floaters','Flashes of light','Shadow or curtain over vision','Distorted or wavy vision','Gradual loss of central vision','Dark spots in vision'],
    types: [
      { name: 'Anti-VEGF Injections', desc: 'Intravitreal injections to stop abnormal blood vessel growth in wet AMD and diabetic retinopathy.' },
      { name: 'Retinal Laser (Photocoagulation)', desc: 'Laser treatment to seal leaking blood vessels or create barriers around retinal tears.' },
      { name: 'Vitrectomy', desc: 'Microsurgery to remove vitreous gel and repair detached retina, macular holes, or epiretinal membranes.' },
      { name: 'Scleral Buckling', desc: 'External silicone band placed around the eye to push the wall toward the detached retina.' },
    ],
    lensOptions: [],
    preparation: ['Dilated fundus examination','OCT (Optical Coherence Tomography) scan','Fluorescein angiography if needed','Blood sugar control for diabetic patients','Arrange for someone to drive you home'],
    aftercare: ['Maintain specific head positioning if gas bubble is used','Use prescribed eye drops diligently','Avoid air travel if gas bubble is present','Regular follow-up imaging scans','Monitor for any vision changes and report immediately'],
    faqs: [
      { q: 'Can diabetic retinopathy be reversed?', a: 'Early stages can be managed effectively with blood sugar control and treatment. Advanced stages can be treated to prevent further vision loss, but lost vision may not be fully recoverable.' },
      { q: 'How urgent is retinal detachment?', a: 'Retinal detachment is a medical emergency. Seek immediate treatment — delay can lead to permanent vision loss.' },
    ],
  },
  glaucoma: {
    title: 'Glaucoma Treatment',
    subtitle: 'Preserving Vision Before It\'s Too Late',
    heroImage: 'https://images.unsplash.com/photo-1551884170-09fb70a3a2ed?auto=format&fit=crop&q=80&w=1200',
    overview: 'Glaucoma is a group of eye conditions that damage the optic nerve, often due to elevated intraocular pressure (IOP). Known as the "silent thief of sight," it progresses without symptoms until significant vision is lost. Early detection through regular screening is crucial.',
    duration: '15-45 minutes',
    recovery: '1-4 weeks',
    anesthesia: 'Topical/Local',
    successRate: '90%+',
    costRange: '₹10,000 – ₹80,000',
    symptoms: ['Gradual loss of peripheral (side) vision','Tunnel vision in advanced stages','Eye pain or redness (acute angle-closure)','Halos around lights','Headaches with eye strain','Often NO symptoms in early stages'],
    types: [
      { name: 'Medications (Eye Drops)', desc: 'First-line treatment to reduce IOP through prostaglandin analogs, beta-blockers, or carbonic anhydrase inhibitors.' },
      { name: 'Selective Laser Trabeculoplasty (SLT)', desc: 'Gentle laser applied to the drainage angle to improve fluid outflow. Repeatable and safe.' },
      { name: 'Trabeculectomy', desc: 'Surgical creation of a new drainage channel to lower eye pressure when medications and laser are insufficient.' },
      { name: 'MIGS (Micro-Invasive Glaucoma Surgery)', desc: 'Minimally invasive procedures using tiny stents or devices for safer, faster recovery.' },
    ],
    lensOptions: [],
    preparation: ['Comprehensive glaucoma evaluation','Visual field test (perimetry)','OCT of optic nerve head','Gonioscopy to examine drainage angle','Review of current medications'],
    aftercare: ['Continue prescribed eye drops as directed','Avoid strenuous activity for 2 weeks after surgery','Attend regular IOP monitoring appointments','Never stop glaucoma medications without consulting your doctor','Annual visual field testing'],
    faqs: [
      { q: 'Can glaucoma be cured?', a: 'Glaucoma cannot be cured, but it can be effectively managed. Treatment focuses on lowering eye pressure to prevent further optic nerve damage.' },
      { q: 'Who is at risk for glaucoma?', a: 'Risk factors include age over 40, family history, high eye pressure, diabetes, high myopia, and previous eye injuries.' },
    ],
  },
  cornea: {
    title: 'Cornea Services',
    subtitle: 'Clarity Starts at the Surface',
    heroImage: 'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&q=80&w=1200',
    overview: 'The cornea is the clear, dome-shaped front surface of your eye that plays a crucial role in focusing vision. Our cornea specialists treat conditions ranging from infections and keratoconus to corneal scarring, offering advanced procedures including corneal transplants.',
    duration: '30-90 minutes',
    recovery: '3-12 months',
    anesthesia: 'Local/General',
    successRate: '90%+',
    costRange: '₹30,000 – ₹2,50,000',
    symptoms: ['Blurred or distorted vision','Eye pain or sensitivity to light','Corneal opacity or scarring','Progressive thinning of cornea','Severe dry eyes','Recurrent corneal erosions'],
    types: [
      { name: 'Penetrating Keratoplasty (PK)', desc: 'Full-thickness corneal transplant replacing the entire damaged cornea with a donor cornea.' },
      { name: 'DALK (Deep Anterior Lamellar Keratoplasty)', desc: 'Partial-thickness transplant preserving the patient\'s inner corneal layer, reducing rejection risk.' },
      { name: 'DSEK/DMEK', desc: 'Endothelial keratoplasty replacing only the innermost corneal layer for conditions like Fuchs dystrophy.' },
      { name: 'Corneal Collagen Cross-Linking (C3R)', desc: 'UV-riboflavin treatment to strengthen and stabilize the cornea in keratoconus.' },
    ],
    lensOptions: [],
    preparation: ['Detailed corneal evaluation and topography','Pachymetry and specular microscopy','Blood tests and medical clearance','Discussion of donor tissue availability','Understanding realistic recovery expectations'],
    aftercare: ['Strict adherence to anti-rejection eye drops','Protect eye from injury','Regular follow-up for graft monitoring','Suture removal at scheduled intervals','Vision may continue improving for up to 12 months'],
    faqs: [
      { q: 'How long does a corneal transplant last?', a: 'A successful corneal transplant can last many years to decades with proper care and medication compliance.' },
      { q: 'What is keratoconus?', a: 'Keratoconus is a progressive condition where the cornea thins and bulges into a cone shape, causing distorted vision. C3R can halt its progression.' },
    ],
  },
  pediatric: {
    title: 'Pediatric Eye Care',
    subtitle: 'Gentle Expert Care for Little Eyes',
    heroImage: 'https://images.unsplash.com/photo-1587654780291-39c9404d7dd0?auto=format&fit=crop&q=80&w=1200',
    overview: 'Children\'s eyes are still developing, making early detection and treatment of vision problems critical. Our pediatric ophthalmologists specialize in diagnosing and treating conditions like squint (strabismus), lazy eye (amblyopia), congenital cataracts, and refractive errors in a child-friendly environment.',
    duration: 'Varies by procedure',
    recovery: 'Varies',
    anesthesia: 'General (for surgery)',
    successRate: '95%+',
    costRange: '₹5,000 – ₹1,50,000',
    symptoms: ['Misaligned or crossed eyes','Squinting or closing one eye','Tilting head to see','Sitting too close to TV','Difficulty reading or poor school performance','Excessive tearing or eye rubbing','White reflex in pupil'],
    types: [
      { name: 'Squint (Strabismus) Surgery', desc: 'Precise adjustment of eye muscles to align the eyes, often performed under general anesthesia.' },
      { name: 'Amblyopia (Lazy Eye) Treatment', desc: 'Patching therapy, atropine drops, or vision therapy to strengthen the weaker eye.' },
      { name: 'Pediatric Cataract Surgery', desc: 'Removal of congenital or developmental cataracts with or without IOL implantation.' },
      { name: 'ROP Screening & Treatment', desc: 'Screening and laser treatment for Retinopathy of Prematurity in premature infants.' },
    ],
    lensOptions: [],
    preparation: ['Child-friendly comprehensive eye exam','Cycloplegic refraction for accurate measurement','Assessment of binocular vision','Pre-anesthetic evaluation for surgery cases','Reassure the child with age-appropriate explanations'],
    aftercare: ['Follow patching or medication schedule strictly','Regular follow-up visits as vision develops','Monitor for recurrence of squint','Encourage outdoor activities for myopia prevention','Annual comprehensive eye exams throughout childhood'],
    faqs: [
      { q: 'At what age should my child first see an eye doctor?', a: 'The first eye screening should be at 6 months, then at age 3, and before starting school. Children with risk factors should be examined earlier.' },
      { q: 'Will my child outgrow crossed eyes?', a: 'True strabismus does not resolve on its own and requires treatment. Early intervention gives the best outcomes. Pseudo-strabismus (flat nasal bridge) is common in infants and resolves naturally.' },
    ],
  },
};

export type TreatmentSlug = keyof typeof treatments;
export const treatmentSlugs = Object.keys(treatments) as TreatmentSlug[];
